{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{let site_url=ezini("SiteSettings","SiteURL")}
{set-block scope=root variable=subject}{"%siteurl new password"|i18n("eregistry/password/user",,hash('%siteurl',$site_url))}{/set-block}
{"Your account information"|i18n('eregistry/password/user')}
{"Email"|i18n('eregistry/password/user')}: {$user.email}

{if $link}
{"Click here to get new password"|i18n('eregistry/password/user')}:
{concat("user/forgotpassword/", $hash_key, '/')|ezurl(no,'full')}
{else}


{if $password}
{"New password"|i18n('eregistry/password/user')}: {$password}
{/if}

{/if}

{/let}
