{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{default attribute_base='ContentObjectAttribute'}
{def $attribute_content=$attribute.content}

{* Current image. *}

<div class="form-group">

{if $attribute_content.original.is_valid}
    {if is_unset($register)}<label>{'Current image'|i18n( 'design/standard/content/datatype' )}</label>{/if}
    <table class="list" cellspacing="0">
        <tr>
            <th class="tight">{'Preview'|i18n( 'design/standard/content/datatype' )}</th>
            <th>{'Filename'|i18n( 'design/standard/content/datatype' )}</th>
            <th>{'MIME type'|i18n( 'design/standard/content/datatype' )}</th>
            <th>{'Size'|i18n( 'design/standard/content/datatype' )}</th>
        </tr>
        <tr>
            <td>{attribute_view_gui image_class=ezini( 'ImageSettings', 'DefaultEditAlias', 'content.ini' ) attribute=$attribute}</td>
            <td>{$attribute.content.original.original_filename|wash( xhtml )}</td>
            <td>{$attribute.content.original.mime_type|wash( xhtml )}</td>
            <td>{$attribute.content.original.filesize|si( byte )}</td>
        </tr>
    </table>
{else}
    {if is_unset($register)}<p>{'There is no image file.'|i18n( 'design/standard/content/datatype' )}</p>{/if}
{/if}

{if is_unset($register)}
    {if $attribute_content.original.is_valid}
        <input class="btn btn-warning" type="submit" name="CustomActionButton[{$attribute.id}_delete_image]" value="{'Remove image'|i18n( 'design/standard/content/datatype' )}" />
    {else}
        <input class="btn btn-disabled" type="submit" name="CustomActionButton[{$attribute.id}_delete_image]" value="{'Remove image'|i18n( 'design/standard/content/datatype' )}" disabled="disabled" />
    {/if}
{/if}
</div>

    {* New image file for upload. *}
    <div class="form-group">
        <input type="hidden" name="MAX_FILE_SIZE" value="{$attribute.contentclass_attribute.data_int1|mul( 1024, 1024 )}" />
        {if is_unset($register)}<label for="ezcoa-{if ne( $attribute_base, 'ContentObjectAttribute' )}{$attribute_base}-{/if}{$attribute.contentclassattribute_id}_{$attribute.contentclass_attribute_identifier}_file">{'New image file for upload'|i18n( 'design/standard/content/datatype' )}</label>{/if}
        <input id="ezcoa-{if ne( $attribute_base, 'ContentObjectAttribute' )}{$attribute_base}-{/if}{$attribute.contentclassattribute_id}_{$attribute.contentclass_attribute_identifier}_file" class="btn ezcc-{$attribute.object.content_class.identifier} ezcca-{$attribute.object.content_class.identifier}_{$attribute.contentclass_attribute_identifier}" name="{$attribute_base}_data_imagename_{$attribute.id}" type="file" />
    </div>

{if is_unset($register)}
    {* Alternative image text. *}
    <div class="form-group">
        <label for="ezcoa-{if ne( $attribute_base, 'ContentObjectAttribute' )}{$attribute_base}-{/if}{$attribute.contentclassattribute_id}_{$attribute.contentclass_attribute_identifier}_alttext">{'Alternative image text'|i18n( 'design/standard/content/datatype' )}</label>
        <input class="form-control" id="ezcoa-{if ne( $attribute_base, 'ContentObjectAttribute' )}{$attribute_base}-{/if}{$attribute.contentclassattribute_id}_{$attribute.contentclass_attribute_identifier}_alttext" class="box ezcc-{$attribute.object.content_class.identifier} ezcca-{$attribute.object.content_class.identifier}_{$attribute.contentclass_attribute_identifier}" name="{$attribute_base}_data_imagealttext_{$attribute.id}" type="text" value="{$attribute_content.alternative_text|wash(xhtml)}" />
    </div>
{/if}

{/default}


