system:
    default:
        field_templates:
            - { template: "@NetgenBirthday/ezbirthday_content_field.html.twig", priority: 0 }
        fielddefinition_settings_templates:
            - { template: "@NetgenBirthday/field_definition/view/ezbirthday.html.twig", priority: 0 }
