services:
    netgen_birthday.field_type:
        class: Netgen\Bundle\BirthdayBundle\Core\FieldType\Birthday\Type
        parent: Ibexa\Core\FieldType\FieldType
        tags:
            - { name: ibexa.field_type, alias: ezbirthday }

    netgen_birthday.field_type.legacy.converter:
        class: Netgen\Bundle\BirthdayBundle\Core\Persistence\Legacy\Content\FieldValue\Converter\Birthday
        tags:
            - { name: ibexa.field_type.storage.legacy.converter, alias: ezbirthday }

    netgen_birthday.field_type.indexable:
        class: Ibexa\Core\FieldType\Unindexed
        tags:
            - { name: ibexa.field_type.indexable, alias: ezbirthday }
