services:
    netgen_birthday.field_type:
        class: Netgen\Bundle\BirthdayBundle\Core\FieldType\Birthday\Type
        parent: ezpublish.fieldType
        tags:
            - { name: ezplatform.field_type, alias: ezbirthday }

    netgen_birthday.field_type.legacy.converter:
        class: Netgen\Bundle\BirthdayBundle\Core\Persistence\Legacy\Content\FieldValue\Converter\Birthday
        tags:
            - { name: ezplatform.field_type.legacy_storage.converter, alias: ezbirthday }

    netgen_birthday.field_type.indexable:
        class: eZ\Publish\Core\FieldType\Unindexed
        tags:
            - { name: ezplatform.field_type.indexable, alias: ezbirthday }
