{* DO NOT EDIT THIS FILE! Use an override template instead. *}
    {default $view_parameters=array()}
    {foreach $content_attributes as $ContentObjectAttribute}
    <div class="block ezcca-edit-datatype-{$ContentObjectAttribute.data_type_string} ezcca-edit-{$ContentObjectAttribute.contentclass_attribute_identifier}">

    {* only show edit GUI if we can edit *}
    {if and(eq($ContentObjectAttribute.contentclass_attribute.can_translate,0),
                      ne($object.initial_language_code,$ContentObjectAttribute.language_code) ) }
        <label>{$ContentObjectAttribute.contentclass_attribute.name|wash|d18n('attribute/edit')}</label><div class="labelbreak"></div>
        <input type="hidden" name="ContentObjectAttribute_id[]" value="{$ContentObjectAttribute.id}" />
        {attribute_view_gui attribute_base=$attribute_base attribute=$ContentObjectAttribute view_parameters=$view_parameters}
        </div>
    {else}
        <label{if $ContentObjectAttribute.has_validation_error} class="validation-error"{/if}>{$ContentObjectAttribute.contentclass_attribute.name|wash}</label><div class="labelbreak"></div>
        <input type="hidden" name="ContentObjectAttribute_id[]" value="{$ContentObjectAttribute.id}" />
        {attribute_edit_gui attribute_base=$attribute_base attribute=$ContentObjectAttribute view_parameters=$view_parameters}
        </div>

    {/if}

    {/foreach}
    {/default}
